sudo: false

language: node_js
node_js:
  - "lts/*"

services:
  - docker

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test

deploy:
  skip_cleanup: true
  provider: script
  script: make publish
  on:
    branch: master
    tags: true