sudo: required
language: node_js
node_js:
- lts/*
services:
- docker
install:
- npm install
script:
- npm run lint
- npm run build
- npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: >-
    echo $DOCKER_HUB_USERNAME &&
    echo $DOCKER_HUB_PASSWORD &&
    echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin && 
    docker build -t joelsummerfield/experiment.typescript-service . &&
    docker tag joelsummerfield/experiment.typescript-service joelsummerfield/experiment.typescript-service:${TRAVIS_TAG#?} &&
    docker push joelsummerfield/experiment.typescript-service
  on:
    branch: master
    tags: true
env:
  global:
  - secure: l8kJhPRLEcqjFl+1423XoSQ93smErEl2Ho8hAedxzKohRu5gSgfdz63avyzFbWZIgFABl8Y3t2kPwWY1G7QTcVmQfqQuy/Dz8HKg1+CLL4kDb5R2SIhijSLz2QKvMAvXlnsmu0kOI+Oe7//4vhvnGzFoj5PAt1tTSSVbqdrRZKngv2dR9MqgHO+llZOv1cVSJAqfCDmn8aJlsQWPJIvjT2HDDylUtnmrn9Wa6PjzsI0xbHFxzyDEIX1TQ7iW/vAYC+W7pJ/KH2XlyfQYP2ZKsui+Y30lgpQHQgksXX8zjVbvisrcCwRKMOn6z5NH+bCG4dyAwQ3YzsQd7R9vsOSnZh49PEQzrPS9gNC9wuFogn3IFHHhl3QHsrdAArt0VzoXZ0eUS6rmLBb7FONpzclKGRRviN4LVkUZK0jnk2pbr2mONsbzb0VOyxo+zJrgdbeOL6ObXNS+/3VhXRYA8pH/RzCkdfyX/o2hJJIsOg0iPGEueEMpt1K/SxG2Gii8l2IztSiAr5ZhqNXOPRCPX0oBgV3Vmi16o7XPIop2GyinpA9W4Ha+PB2YrwB+TTICnhZPRqLb9LJUDHjHmh2cO/HxSjseWt15B57bkt6sOv2F4TY1b+RQNJaxHZei0y0CoGHsU32BzpLGPj+h/jtNkU9fG3NB/Zp2Ce0jPIh1W/zaWSY=
  - secure: DPB5kTcXKSrDyM68XAUGLaFEPOHd1gYPKgSjuuPJQA4gbhTQp9wGrfYZ9WDPUzgIoJC3s6EWHLUqK3mAP1NfLVUW4v23dD+sfrz3foTMMoz/ETxm3w8dFkWre3XTVI+8BG62IAj8U6puw4IxwqDFbTFUBzmXVX9Q3N9OvVHM5e2M1rsiDUHRBkTqy9yp0Rq9t7N6a5nFg5gRquyYIurbbbwrqmnoP1CzdOSU7MRBQg43TZmwjhXk/XF0Byog3QFAXK8k9vFb5XCVobVw++JnICnxqMDjrnNuk3LAFUeUszf5n0Cnp4RoqNWtBDXAw6T3UzTkJD+GHPKf3N1/ugeXFlw3ws5j5PNnVTSnCIR2nNNESousd9u1KYUURZO14tAY28o4coMJ7Bjbvv1OfA1vFe+mURuylaJ7w/7kM26tEZXl0d0hreHHtTlgN35Fm0yare5UjADQVhvNWN0+U0B5KTCKidB/tVxvf4TmjoMbS4Y+9lWhXKJ/+zq/E1byOwUTZERcRuqMrAItGW4dX86+hpG1TV2zrh/XEho+OgmvGuB/2JsvzYRBz0w3zlwtklyT4lKOqGbpXLRbAkAY4mJFunrBPgPfUKPXxdje8Z4OwDZeXuCjVCM0f8N3wAHwD8S3sWKav3ae2Ky6dZE6ihjo2CfaHkdFXKz6QG7rduUlgzA=
