sudo: false

language: node_js
node_js:
  - "lts/*"

services:
  - docker

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test

deploy:
  skip_cleanup: true
  provider: script
  script: >-
    echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin &&
    docker build -t joelsummerfield/experiment.typescript-service . &&
    docker tag joelsummerfield/experiment.typescript-service joelsummerfield/experiment.typescript-service:${TRAVIS_TAG#?} &&
    docker push joelsummerfield/experiment.typescript-service
  on:
    branch: master
    tags: true