sudo: required
language: node_js
node_js:
- lts/*
services:
- docker
install:
- npm install
script:
- npm run lint
- npm run build
- npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: >-
    echo $DOCKER_HUB_USERNAME &&
    echo $DOCKER_HUB_PASSWORD &&
    echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin && 
    docker build -t joelsummerfield/experiment.typescript-service . &&
    docker tag joelsummerfield/experiment.typescript-service joelsummerfield/experiment.typescript-service:${TRAVIS_TAG#?} &&
    docker push joelsummerfield/experiment.typescript-service
  on:
    branch: master
    tags: true
env:
  global:
  - secure: l8kJhPRLEcqjFl+1423XoSQ93smErEl2Ho8hAedxzKohRu5gSgfdz63avyzFbWZIgFABl8Y3t2kPwWY1G7QTcVmQfqQuy/Dz8HKg1+CLL4kDb5R2SIhijSLz2QKvMAvXlnsmu0kOI+Oe7//4vhvnGzFoj5PAt1tTSSVbqdrRZKngv2dR9MqgHO+llZOv1cVSJAqfCDmn8aJlsQWPJIvjT2HDDylUtnmrn9Wa6PjzsI0xbHFxzyDEIX1TQ7iW/vAYC+W7pJ/KH2XlyfQYP2ZKsui+Y30lgpQHQgksXX8zjVbvisrcCwRKMOn6z5NH+bCG4dyAwQ3YzsQd7R9vsOSnZh49PEQzrPS9gNC9wuFogn3IFHHhl3QHsrdAArt0VzoXZ0eUS6rmLBb7FONpzclKGRRviN4LVkUZK0jnk2pbr2mONsbzb0VOyxo+zJrgdbeOL6ObXNS+/3VhXRYA8pH/RzCkdfyX/o2hJJIsOg0iPGEueEMpt1K/SxG2Gii8l2IztSiAr5ZhqNXOPRCPX0oBgV3Vmi16o7XPIop2GyinpA9W4Ha+PB2YrwB+TTICnhZPRqLb9LJUDHjHmh2cO/HxSjseWt15B57bkt6sOv2F4TY1b+RQNJaxHZei0y0CoGHsU32BzpLGPj+h/jtNkU9fG3NB/Zp2Ce0jPIh1W/zaWSY=
  - secure: ozQb3XNU4hEs8f4RbZQsNrZFzoeR9YEjUBaq1PXepMMVra/UPoxJ8L5Lo39snXDstILomziYAJ2mUUD4cmYwsVu/9Mm8r63fL+TZSpqxuy/b5YGPWKdRIp65R6KGdbgBj0htC/yMpOaHuh0O5JDaoW15QXaWMlrajwMdOlKQ56jdNrmUWCoA4I62m94mxJXC7YtbGXS5i1HBU+Oh67eL/HGkJkAKjIKdilUFzrJ50BazsTmhpDPWlDpaTuzLiqLWXxLoCpon04umRE1NexLBEY85xW0NGEt74RE7Fqrmb8ejB3Mi4Sn+MMNbcN6fyPBt/4hvy95maDRDLbCV9T5VodaCGbmXkjrk4Hdlk6H81YgPsaZKUJ6G9a5NTEIUil4us33un5Z4hSFRm7utfgZZ+zLTKgz5uVVv83PwaD8/JuWQzkkyM/j7fGk6pOIyrP/b3LDB6dxUyn8GfrWu+UUzYAY6+HlNCqyrLtEHA9vo58rrUgsHYQD6BS9dnNnn1G4bRDfsdPmYAvPp+VzCaZGFbOteHb/10KPbjM5aDy+I4yBbSYlnrVlNZmOfW1fgYwBkksii1MNx9NUBOttfNlkAunlx14zaISpCcFz32aulcdXuIaoN7Qz6tgbCRE5dne/SxVbPUddJT/naC5VjSqXOXFF7jod5Ad22YUWdt9wU8R0=
