name: Continuous Integration

on:
  push:
    branches:
      - master
    tags:        
      - v*
  pull_request:

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checking code for styling issues
        run: |
          make format
      - name: Checking code for linting issues
        run: |
          make lint
      - name: Checking unit tests pass
        run: |
          make test
      - name: Checking 'debug' code builds
        run: |
          sudo make debug
      - name: Checking 'release' code builds
        run: |
          sudo make release
      - name: Checking 'container' builds
        run: |
          docker build --no-cache -t $REPO_NAME .
        env:
          REPO_NAME: ${{ github.event.repository.name }}
